KERNEL_PATH=/lib/modules/${kernelver}/build
export OS_VENDOR_V1=1
AUTOINSTALL="yes"
VENDOR_CFLAGS="-DOS_VENDOR_V1=1"
PACKAGE_NAME="ub-os-component-dkms"
PACKAGE_VERSION="1.0.2"

MAKE[0]="make KERNEL_PATH=${KERNEL_PATH} VENDOR_CFLAGS=${VENDOR_CFLAGS}"
CLEAN="make clean"

BUILT_MODULE_NAME[0]="ummu-core"
BUILT_MODULE_LOCATION[0]="drivers/iommu/hisilicon/ummu-core"
DEST_MODULE_LOCATION[0]="/updates"

BUILT_MODULE_NAME[1]="ummu"
BUILT_MODULE_LOCATION[1]="drivers/iommu/hisilicon"
DEST_MODULE_LOCATION[1]="/updates"

BUILT_MODULE_NAME[2]="ubmem_vmmu"
BUILT_MODULE_LOCATION[2]="drivers/iommu/hisilicon/ubmem-mmu"
DEST_MODULE_LOCATION[2]="/updates"

BUILT_MODULE_NAME[3]="odf"
BUILT_MODULE_LOCATION[3]="drivers/firmware/uvb"
DEST_MODULE_LOCATION[3]="/updates"

BUILT_MODULE_NAME[4]="cis"
BUILT_MODULE_LOCATION[4]="drivers/firmware/uvb"
DEST_MODULE_LOCATION[4]="/updates"

BUILT_MODULE_NAME[5]="ub_fwctl"
BUILT_MODULE_LOCATION[5]="drivers/fwctl/ub"
DEST_MODULE_LOCATION[5]="/updates"

BUILT_MODULE_NAME[6]="ummu-pmu"
BUILT_MODULE_LOCATION[6]="drivers/perf/hisilicon"
DEST_MODULE_LOCATION[6]="/updates"

BUILT_MODULE_NAME[7]="ubase"
BUILT_MODULE_LOCATION[7]="drivers/ub/ubase"
DEST_MODULE_LOCATION[7]="/updates"

BUILT_MODULE_NAME[8]="uburma"
BUILT_MODULE_LOCATION[8]="drivers/ub/urma/uburma"
DEST_MODULE_LOCATION[8]="/updates"

BUILT_MODULE_NAME[9]="ubcore"
BUILT_MODULE_LOCATION[9]="drivers/ub/urma/ubcore"
DEST_MODULE_LOCATION[9]="/updates"

BUILT_MODULE_NAME[10]="ubagg"
BUILT_MODULE_LOCATION[10]="drivers/ub/urma/ubagg"
DEST_MODULE_LOCATION[10]="/updates"

BUILT_MODULE_NAME[11]="ipourma"
BUILT_MODULE_LOCATION[11]="drivers/ub/urma/ulp/ipourma"
DEST_MODULE_LOCATION[11]="/updates"

BUILT_MODULE_NAME[12]="udma"
BUILT_MODULE_LOCATION[12]="drivers/ub/urma/hw/udma"
DEST_MODULE_LOCATION[12]="/updates"

BUILT_MODULE_NAME[13]="obmm"
BUILT_MODULE_LOCATION[13]="drivers/ub/obmm"
DEST_MODULE_LOCATION[13]="/updates"

BUILT_MODULE_NAME[14]="sentry_remote_reporter"
BUILT_MODULE_LOCATION[14]="drivers/ub/sentry"
DEST_MODULE_LOCATION[14]="/updates"

BUILT_MODULE_NAME[15]="sentry_reporter"
BUILT_MODULE_LOCATION[15]="drivers/ub/sentry"
DEST_MODULE_LOCATION[15]="/updates"

BUILT_MODULE_NAME[16]="sentry_msg_helper"
BUILT_MODULE_LOCATION[16]="drivers/ub/sentry"
DEST_MODULE_LOCATION[16]="/updates"

BUILT_MODULE_NAME[17]="ubdevshm"
BUILT_MODULE_LOCATION[17]="drivers/ub/ubdevshm"
DEST_MODULE_LOCATION[17]="/updates"

BUILT_MODULE_NAME[18]="hisi_ubus"
BUILT_MODULE_LOCATION[18]="drivers/ub/ubus/vendor/hisilicon"
DEST_MODULE_LOCATION[18]="/updates"

BUILT_MODULE_NAME[19]="ubus"
BUILT_MODULE_LOCATION[19]="drivers/ub/ubus"
DEST_MODULE_LOCATION[19]="/updates"

BUILT_MODULE_NAME[20]="ubmempfd"
BUILT_MODULE_LOCATION[20]="drivers/ub/ubmempfd"
DEST_MODULE_LOCATION[20]="/updates"

BUILT_MODULE_NAME[21]="ubfi"
BUILT_MODULE_LOCATION[21]="drivers/ub/ubfi"
DEST_MODULE_LOCATION[21]="/updates"

BUILT_MODULE_NAME[22]="cdma"
BUILT_MODULE_LOCATION[22]="drivers/ub/cdma"
DEST_MODULE_LOCATION[22]="/updates"

BUILT_MODULE_NAME[23]="vfio-ub"
BUILT_MODULE_LOCATION[23]="drivers/vfio/ubus"
DEST_MODULE_LOCATION[23]="/updates"

BUILT_MODULE_NAME[24]="unic"
BUILT_MODULE_LOCATION[24]="drivers/net/ub/unic"
DEST_MODULE_LOCATION[24]="/updates"

BUILT_MODULE_NAME[25]="ubl"
BUILT_MODULE_LOCATION[25]="drivers/net/ub/dev"
DEST_MODULE_LOCATION[25]="/updates"
