#!/bin/sh
set -e

PKG_NAME=ub-os-component-dkms
PKG_VERSION=1.0.2

if [ "$1" = "configure" ] && [ -n "${PKG_VERSION}" ]; then
	dkms add -m ${PKG_NAME} -v ${PKG_VERSION} || true
	dkms build -m ${PKG_NAME} -v ${PKG_VERSION} || true
	dkms install -m ${PKG_NAME} -v ${PKG_VERSION} || true
fi